# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('teacher_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('school_class', models.IntegerField(choices=[(1, '1a'), (2, '1b'), (3, '2a'), (4, '2b'), (5, '3a'), (6, '3b')])),
                ('grades', models.ManyToManyField(to='exercises.SchoolSubject')),
            ],
        ),
    ]
