# Generated by Django 2.0.12 on 2019-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.IntegerField(choices=[(0, '1a'), (1, '1b'), (2, '2a'), (3, '2b'), (4, '3a'), (5, '3b')]),
        ),
    ]
