# Generated by Django 2.0.12 on 2019-08-10 08:32

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_presencelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsubject',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nazwa przedmiotu'),
        ),
        migrations.AlterField(
            model_name='schoolsubject',
            name='teacher_name',
            field=models.CharField(help_text='Nauczyciel powienien miec imie i nazwisko', max_length=64, validators=[exercises.models.validate_teacher_name], verbose_name='nazwa nauczyciela'),
        ),
    ]
