# Generated by Django 2.0.12 on 2019-08-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('od', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.SchoolSubject')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='od',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exercises.Student'),
        ),
    ]
